window:
  decorations: None
  startup_mode: Maximized
  dynamic_title: true
scrolling:
  history: 100000
  multiplier: 3


# Colors (Darcula)
# https://github.com/doums/darcula/blob/master/color_sources.md
colors:
  # Default colors
  primary:
    background: '0x2b2b2b'
    foreground: '0xa9b7c6'

  # Normal colors
  normal: 
    black:   '0xffffff'
    red:     '0xff6b68'
    green:   '0xa8c023'
    yellow:  '0xd6bf55'
    blue:    '0x5394ec'
    magenta: '0xae8abe'
    cyan:    '0x299999'
    white:   '0x1f1f1f'

  # Bright colors
  bright:
    black:   '0x555555'
    red:     '0xff8785'
    green:   '0xa8c023'
    yellow:  '0xffff00'
    blue:    '0x7eaef1'
    magenta: '0xff99ff'
    cyan:    '0x6cdada'
    white:   '0x999999'

font:
  normal:
    family: "MesloLGS NF"
    style: Regular
  bold:
    family: "MesloLGS NF"
    style: Bold
  italic:
    family:  "MesloLGS NF"
    style: Italic
  bold_italic:
    family:  "MesloLGS NF"
    style: Bold Italic
  size: 12.0
  offset:
  #  x: 0
    y: 5
live_config_reload: true

